### ISSUE TITLE
The Meta files are missing.

### ISSUE THREAD

**Issue by Endarren** [kiml42/SpaceCombatSimulation#2]
Your zip of the project does not have any of the .meta files. Without those, most of the set up on prefabs and in scenes is completely gone. You need to include the meta files of everything from your project.  Without this working, I can't see what your example scenes do.

**Comment by kiml42** [comment]
Thanks for the heads up, I'll fix that now.
Thanks for looking at my project too, I have no idea how you came by it.

**Comment by kiml42** [comment]
I think that's fixed now, but there's another sort of .meta file sti;ll in the gitignore, so would you kindly test it for me? Thanks again.

**Comment by Endarren** [comment]
I look through Github for projects involving Unity for anything that look interesting.  I like seeing howother coders in Unity do things.  It still doesn't work.  Each prefab and scene is supposed to have their own meta file, of the same name of each.  Once those meta files are included, the prefabs and scenes should work.   I was able to get some of the scripts to work by remaking the prefabs, and it good work.

**Comment by kiml42** [comment]
I'm really annoyed with myself now. I made the right changes and forgot to push the commit. Should work now (for real this time).

I'd love to know what you think of it when you have it working correctly.

**Comment by Endarren** [comment]
Don't worry, I've made mistakes like that before.  

I will.

**Comment by Endarren** [comment]
It works!

**Comment by Endarren** [comment]
I'll give you my feedback in a few days, after I try out everything.  Thank you.

**Comment by Endarren** [comment]
I looked over what you've made and it's a good start.  It reminds me of the Homeworld games a bit.  I am interested in seeing where you take it.  I do have some feedback.

- I love the modular design of the turrets and engines.  I would suggest an option to just disable the object at zero health, instead of destroying it.

- I would suggest when you spawn in projectile that you parent them to an empty game object.  That way, the project heirchy is not messy.  I wrote up a Projectile script that does that.  I made a fork of this project and put the script in it.  You can find it here https://github.com/Endarren/SpaceCombatSimulation/blob/master/Assets/src/Projectile.cs

- I would suggest using Scriptable Objects to hold data, such as projectile speed and damage.  This would save memory, since you wouldn't have duplicate data in objects.

- I would suggest using a different method to detect enemies.  GameObject.FindGameObjectsWithTag is not very effiecent.

- To make it more customizable, it would be nice if the turret turn speeds were changable in the inspector.
- You might want to make the OnCollisionEnter for HealthController do some checks to make sure certain colliders do not accidently do damage.  I was playing around with putting a shield around a ship.  I had to make it ignore all the colliders of the ship so it didn't blow up.

I do like the work you have done, and I hope you continue to add more and improve what you have.

**Comment by kiml42** [comment]
Thanks for your feedback, There's lots of really useful stuff there. I just finished playing the Homeworld Remasterd games when I started this. I really enjoyed watching the turrests on the ships tracking the enemies, but was a little disapointed by their simplicity, as each turret is just a single object, rather than having the two parts for the two different axies. This will probably be even more homeworldy if I ever get round to programming fighters.

- Thats a good idea, I'll make it an option for the health controller, probably at the same time as I do passing damage up to parent's health.

- That would make things much neater, the hierarchy does get very cluttered. For adding your code to the project, the best thing to do would be to create a branch instead of a fork. That way you can make a pull request to ask me to merge it into master.

- I've never heard of scriptable objects, I'll have to look into that.

- Thanks for the suggestion. My current idea is to have every bahaviour register it's self as a PotentialTarget with a static class that everything will ask for tagets. Do you think that would be more eficient?

- Speed variables for the turret's hingest sound like another good idea.

- I thought about doing shields, but came across the same problem.  Health controller should ignore triggers, but a trigger wouldn't be seen by the beams, so I'll probably approach this by having a tag on the shield that health controller is told to ignore.

Thanks again.

**Comment by kiml42** [comment]
You can actually make pull requests for forks as well as branches. I made one for your fork and merged it in. It works great, much neater than having heaps of projectiles at the top level. I did tweak it quite a bit, so now you can use the same script with any number of groups of different names.

**Comment by Endarren** [comment]
That's great.  The idea you have for PotentialTarget sounds like it could work and would be more efficient.

**Comment by Endarren** [comment]
I just tried out the new version.  The improvements are good.  I like that turrets can now target projectiles.  I would suggest an option for weapons to have allowed target types.  For example, a turret could be set to only target projectiles and not turrets or ships.  It would also help when you introduce smaller crafts, like fighters, so that your flak or anti-fighter weapons only target them.  I like the work you've done so far and am looking forward to seeing it expand.  Also, I liked your target dictionary.  I used your idea to make a tab target system for a prototype game I am working on at my job.  Thank you for that inspiration.

Oh, I almost forgot.  I found this repository on GitHub with the source code for the original Homeworld game.  It's in C, but it might give you some ideas by seeing how they did some of their code.  https://github.com/aheadley/homeworld
